---
## The Helm application being deployed
helm:
  ## The repository containing the helm repository
  repository: https://kubernetes.github.io/ingress-nginx
  ## The chart to install
  chart: ingress-nginx
  ## The chart version to install
  version: "4.11.1"

## Namespace configuration
namespace:
  ## The name of the namespace
  name: ingress-system
  ## Pod Security Policy
  pod_security: privileged
