---
name: Workflow Validation
on:
  push:
    branches:
      - main
    paths:
      - ".github/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/**"

permissions:
  contents: read

jobs:
  validate-workflows:
    uses: appvia/appvia-cicd-workflows/.github/workflows/github-workflow-validation.yml@main
    name: Validate GitHub Workflows
